### ISSUE TITLE
如果需要输入密码程序该如何修改呢？

### ISSUE THREAD

**Issue by MicalShow** [Yoroion/FuckTencentMeeting#1]
如题，谢谢大佬

**Comment by Kyocius** [comment]
1. 鼠标左键点击方法: `Win32Method.LeftMouseClick(int Xposition, int Yposition)`向参数里传入坐标即可。坐标可以通过 `Snipaste` 等软件获取。
2. 键盘输入事件需要调用方法 `new InputSimulator().Keyboard.TextEntry(string str)` 向参数里传入密码。
3. 在`Program.cs`里有一个`Start`函数，在函数中间增加逻辑即可。
4. 望使用愉快😊

**Comment by MicalShow** [comment]
好的，已经完成，感谢大佬

**Comment by Kyocius** [comment]
现在这个项目已经使用 **Spectre.Console** 库重构，现在只需要在**配置区域**修改常量就行了 ~以前的代码太屎了~
而且 FuckTencentMeeting 现已推出更适合普通用户的 [GUI 版](https://github.com/Yoroion/FuckMeetingPlus)
