### ISSUE TITLE
无反应

### ISSUE THREAD

**Issue by sgyueran** [Yoroion/FuckTencentMeeting#2]
![image](https://user-images.githubusercontent.com/43454314/166833822-6f2cdbce-8858-431b-9bc1-ec0f23221df8.png)
确认时间后没有反应

**Comment by Kyocius** [comment]
`var dateTime = DateTime.Now.ToString("dd/H/m")`注意这里的格式

**Comment by Kyocius** [comment]
你应该设置预定时间为`05/6/9`，如果对格式不满意的话可以自己修改字符串格式

**Comment by Kyocius** [comment]
> `var dateTime = DateTime.Now.ToString("dd/H/m")`注意这里的格式

现在这个项目已经使用 Spectre.Console 大规模重构，时间格式也改为了 `HH/mm` 更符合使用逻辑了
