### ISSUE TITLE
使用 Quartz 代替 while

### ISSUE THREAD

**Issue by modcrafts** [Yoroion/FuckTencentMeeting#3]
~~[quartz-scheduler/quartz](https://github.com/quartz-scheduler/quartz)~~
[quartznet/QuartzNET](https://github.com/quartznet/quartznet)

**Comment by Kyocius** [comment]
正在重构下一个大版本，加入 GUI 和 Schedule

**Comment by Kyocius** [comment]
话说为啥要贴出来一个 Java 的定时库？C# 有 [Quartz.NET](https://github.com/quartznet/quartznet) 😂

**Comment by modcrafts** [comment]
> 话说为啥要贴出来一个 Java 的定时库？C# 有 [Quartz.NET](https://github.com/quartznet/quartznet) 😂

发错了😂

**Comment by Kyocius** [comment]
最新的 GUI 版已发布，使用了 Timer 来代替 while 语句，来看看 [FuckMeetingPlus](https://github.com/Yoroion/FuckMeetingPlus)
